controller_list:
  - name: fake_kr_50_r2500_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_parallel_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - right_finger_joint
initial:  # Define initial robot poses per group
#  - group: kr_50_r2500
#    pose: home

  []