simulation_step_time: 0.001
real_step_time : 0.001
camera_init:
  distance: 2.00
  yaw: 128.80
  pitch: -32.60
  target_position: [1.32,1.49,1.64]

joint_state_publish_rate: 250
joint_target_publish_rate: 250
object_tf_publish_rate: 250
##### Cell layout
robots:
- 'kr_50_r2500'
- 'parallel_gripper'
- 'table'

kr_50_r2500:
  start_position: [0,0,0]
  start_orientation: [-1.57,0,0]
  # start_configuration: [-1.58825,-1.29154,1.65806,0,1.20428,0]
  # start_configuration: [0,-1.29154,1.65806,0,1.20428,0]
  start_configuration: [0,0,0,0,0,0]
  fixed: 1    # 1 to fix robot to world, 0 to spawn it unfixed

parallel_gripper:
  start_position: [2.7,0,0.65]
  start_orientation: [0,1.57,0]
  fixed: 0

table:
  start_position: [0,1.5,0]
  start_orientation: [0,0,0]
  fixed: 1    # 1 to fix robot to world, 0 to spawn it unfixed
  package_name: kuka_coke_description
  foulder_name: urdf
  xacro_file_name: 'table_pybullet'   # an urdf file with the same name will be generated
  controlled_joint_name: []
  joint_control_mode : '' # position (which is in fact POSITION_VELOCITY_PD), velocity, torque and pd.

external_constraint:
  - parent_body: 'kr_50_r2500'
    parent_link: 'flange'
    child_body: 'parallel_gripper'
    child_link: 'gripper_base'
    type: 'fixed'             # joint type: prismatic, fixed, point2point, gear
    axis: [0,0,0]                   # joint axis, in child link frame
    parent_frame_position: [0, 0, 0.018] # position of the joint frame relative to parent center of mass frame.
    parent_frame_orientation: [0,0,0,1] # the orientation of the joint frame relative to parent center of mass coordinate frame
    child_frame_position: [0,0,0]   # position of the joint frame relative to a given child center of mass frame (or world origin if no child specified)
    child_frame_orientation: [0,0,0,1]  # the orientation of the joint frame relative to the child center of mass coordinate frame (or world origin frame if no child specified)
    max_force: 10000
####
